Dev us14 crud agendamentos
fga-eps-mds/2022-2-schedula-detalhador-de-chamados pull request #4
Opened 2022-12-11 23:23 UTC by PedroFMuniz

# Pull Request

## 📖 Description

Criação dos endpoints para cadastro,  exclusão, edição e leitura de agendamentos.

### 🎫 Issues

Closes fga-eps-mds/2022-2-Schedula-Doc#17

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

## ⏭ Next Steps

2022-12-12 12:41 UTC, viniciussaturnino requested changes
Restaurar os arquivos:

- app.controller.ts
- app.controller.spec.ts
- app.service.ts

`schedulings` não existe (ing é past continuous, usado para ações contínuas que aconteceram no passado), o certo seria `schedules`.

2022-12-12 12:41 UTC, viniciussaturnino commented on src/app.module.ts
> -import { AppController } from './app.controller';
Manter import

2022-12-12 12:41 UTC, viniciussaturnino commented on src/app.module.ts
> -import { AppService } from './app.service';
Manter import

2022-12-12 12:41 UTC, viniciussaturnino commented on src/app.module.ts
> -  controllers: [AppController],
Manter AppController

2022-12-12 12:41 UTC, viniciussaturnino commented on src/app.module.ts
> -  providers: [AppService],
Manter AppService

2022-12-12 13:20 UTC, PedroFMuniz commented
Alterações realizadas

2022-12-19 00:40 UTC, viniciussaturnino approved these changes
lgtm

2022-12-19 00:40 UTC, merged